version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
     - 9017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: cloth_db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
     - 9018:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    links:
      - mongo
    depends_on:
      - mongo

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django/
    ports:
      - 8000:8000
    depends_on:
      - mongo
